apiVersion: v1
kind: ConfigMap
metadata:
  name: openresty-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |

    pcre_jit on;
    user www-data;
    error_log /dev/stderr warn;
    worker_processes  auto;
    events {
        worker_connections  1024;
    }


    http {
        include       mime.types;
        default_type  application/octet-stream;

        client_body_temp_path /tmp/openresty/nginx-client-body;
        proxy_temp_path /tmp/openresty/nginx-proxy;
        fastcgi_temp_path /tmp/openresty/nginx-fastcgi;
        uwsgi_temp_path /tmp/openresty/nginx-uwsgi;
        scgi_temp_path /tmp/openresty/nginx-scgi;

        sendfile        on;

        keepalive_timeout  65;

        upstream wordpress_backend {
            server wordpress:80;   
        }


        server {
          listen 80 default_server;
          listen [::]:80 default_server;
          
          server_name localhost;
          
          
          location / {
              proxy_pass http://wordpress_backend;
              
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_set_header X-Forwarded-Host $host;
              
          }
          
          location /example {
              default_type 'text/plain';
              content_by_lua_block {
                  ngx.say('Hello, from lua!')
              }
          }
          
          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
              root /opt/openresty/nginx/html;
          }
        }
    }

